// Code generated by Wails v2 (stub for architecture wiring).

export interface ParseResultDTO {
  rawText: string;
  parsedCharacters: Array<{ characterId: number; name: string }>;
  warnings: Array<{ provider: string; code: string; message: string }>;
  parsedAt: string;
}

export interface AnalysisSessionDTO {
  sessionId: string;
  createdAt: string;
  updatedAt: string;
  source: ParseResultDTO;
  pilots: unknown[];
  warnings: Array<{ provider: string; code: string; message: string }>;
}

export function AnalyzePastedText(text: string): Promise<AnalysisSessionDTO> {
  return Promise.resolve({
    sessionId: `session-${Date.now()}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: {
      rawText: text,
      parsedCharacters: [],
      warnings: [],
      parsedAt: new Date().toISOString(),
    },
    pilots: [],
    warnings: [{ provider: 'bootstrap', code: 'PLACEHOLDER', message: 'analysis pipeline not yet connected' }],
  });
}

export function RefreshSession(sessionId: string): Promise<AnalysisSessionDTO> {
  return AnalyzePastedText(sessionId);
}

export function RefreshPilot(): Promise<unknown> {
  return Promise.resolve({});
}

export function LoadRecentSessions(): Promise<AnalysisSessionDTO[]> {
  return Promise.resolve([]);
}

export function LoadSettings(): Promise<Record<string, unknown>> {
  return Promise.resolve({});
}

export function SaveSettings(settings: Record<string, unknown>): Promise<Record<string, unknown>> {
  return Promise.resolve(settings);
}

export function PinPilot(): Promise<Record<string, unknown>> {
  return Promise.resolve({});
}

export function IgnoreCorp(): Promise<Record<string, unknown>> {
  return Promise.resolve({});
}

export function IgnoreAlliance(): Promise<Record<string, unknown>> {
  return Promise.resolve({});
}

export function ClearCache(): Promise<boolean> {
  return Promise.resolve(true);
}
