#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

GENERATED_DIR="frontend/wailsjs"
TS_BINDING="$GENERATED_DIR/go/app/AppService.ts"
SENTINEL="$GENERATED_DIR/.bindings-sentinel"
GO_SERVICE="internal/app/app_service.go"

if [[ ! -f "$TS_BINDING" ]]; then
  echo "missing generated bindings: $TS_BINDING"
  echo "run wails generation first"
  exit 1
fi

mkdir -p "$GENERATED_DIR"

{
  echo "# generated by scripts/update-bindings-sentinel.sh"
  echo "# do not edit by hand"
  echo "methods"
  sed -nE 's/^func \(a \*AppService\) ([A-Z][A-Za-z0-9_]*)\(.*/\1/p' "$GO_SERVICE" | rg -v '^(Startup|Shutdown|SetBuildInfo)$' | sort -u | sed 's/^/method /'
  echo "hashes"
  find "$GENERATED_DIR" -type f ! -name '.bindings-sentinel' -print0 | sort -z | xargs -0 sha256sum | sed 's/^/sha256 /'
} > "$SENTINEL"

echo "updated $SENTINEL"
